import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { extname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const sourceRoot = fileURLToPath(new URL('../src/', import.meta.url))
const outputPath = new URL('../src/generated/icons.ts', import.meta.url)
const references = new Map()
const iconPrefixes = new Set(['icon-park-outline', 'lucide', 'tabler'])
const iconPattern = /["'`]([a-z0-9-]+):([a-z0-9][a-z0-9-]*)["'`]/gi

function walk(directory) {
  const files = []
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name)
    if (entry.isDirectory()) {
      if (entry.name !== 'generated')
        files.push(...walk(path))
    }
    else if (['.ts', '.vue'].includes(extname(entry.name))) {
      files.push(path)
    }
  }
  return files
}

for (const file of walk(sourceRoot)) {
  const source = readFileSync(file, 'utf8')
  for (const match of source.matchAll(iconPattern)) {
    const [, prefix, name] = match
    if (!iconPrefixes.has(prefix))
      continue
    if (!references.has(prefix))
      references.set(prefix, new Set())
    references.get(prefix).add(name)
  }
}

const collections = []
for (const [prefix, requestedNames] of [...references].sort(([a], [b]) => a.localeCompare(b))) {
  const collectionPath = new URL(`../node_modules/@iconify/json/json/${prefix}.json`, import.meta.url)
  if (!existsSync(collectionPath))
    throw new Error(`Missing Iconify collection: ${prefix}`)

  const source = JSON.parse(readFileSync(collectionPath, 'utf8'))
  const names = new Set(requestedNames)
  for (const name of requestedNames) {
    if (!source.icons?.[name] && !source.aliases?.[name])
      throw new Error(`Missing Iconify icon: ${prefix}:${name}`)
  }
  for (const name of [...names]) {
    let alias = source.aliases?.[name]
    while (alias) {
      names.add(alias.parent)
      alias = source.aliases?.[alias.parent]
    }
  }

  const icons = {}
  const aliases = {}
  for (const name of [...names].sort()) {
    if (source.icons[name])
      icons[name] = source.icons[name]
    if (source.aliases?.[name])
      aliases[name] = source.aliases[name]
  }
  collections.push({
    prefix: source.prefix,
    width: source.width,
    height: source.height,
    icons,
    ...(Object.keys(aliases).length ? { aliases } : {}),
  })
}

mkdirSync(new URL('../src/generated/', import.meta.url), { recursive: true })
writeFileSync(
  outputPath,
  `/* eslint-disable style/comma-dangle, style/quote-props, style/quotes */\n// Generated by scripts/generate-icons.mjs. Do not edit.\nexport default ${JSON.stringify(collections, null, 2)}\n`,
)
